import './globals.css'
import type { Metadata } from 'next'
import Providers from './providers'


export const metadata: Metadata = {
  title: 'Linkify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <main className='w-screen min-h-screen bg-gradient-to-br from-[#c2f2ff]  text-foreground bg-background'>
        {children}
        </main>
        </Providers>
      </body>
    </html>
  )
}
